
stages:
  - build

build_chef:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com
    - docker buildx create --name mybuilder --bootstrap --use
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t docker.kodality.com/fsh-chef:latest --push .
  only:
    - master

